default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['TRAVIS'] ? 'postgres' : 'x0y0' %>
  password: <%= ENV['TRAVIS'] ? '' : 'x0y0' %>

development:
  <<: *default
  database: x0y0_development

test:
  <<: *default
  database: x0y0_test

production:
  <<: *default
  database: x0y0_production

sandbox:
  <<: *default
  database: x0y0_production
