common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres
  host: localhost

development:
  database: x0y0_development
  <<: *common

test:
  database: x0y0_test
  <<: *common

production:
  database: x0y0_production
  <<: *common

